name: python odd-even github action

on:
  push:
    branches:
      - master
      - dev

    paths:
      - Odd-or-Even/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repo ls
        run: ls -l
  
