name: python odd-even github action

on:
  push:
    branches:
      - master
      - dev

    paths:
      - Odd-or-Even/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: repo ls
      - run: ls -l
  
