name: python prime number github action

on:
  push:
    branches:
      - master
      - dev

    paths:
      - prime-number/**    
  workflow_dispatch:

jobs:
  Horusec:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
      - name: list repo
        run: ls -l
    
      - name: Downloading Horusec
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
     
      - name: list Horusec
        run: ls -l
      - name: Scanning Service
        run: horusec start -p "./prime-number" -o="json" -O="./results.json"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCEES_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCEES_KEY }}
          aws-region: us-east-1
      
      - name: aws s3 bucket list
        run: aws s3 ls
      

  Build:
    needs: [Horusec]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repo
        run: ls -l

      - name: Update build version
        run: |
          bash scripts/auto_increment_build.sh "prime-number" "build"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Incremented build version"
          add: '*'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gcr_token }}
      - name: docker image
        run: |
          IMAGE_VERSION=`cat tracker/prime-number.version`
          echo "::set-output name=output_version::${IMAGE_VERSION}"
          cd prime-number
          echo $IMAGE_VERSION
          VERSION_SPLIT=(${IMAGE_VERSION//;/ })
          MAIN_VERSION="${VERSION_SPLIT[0]}"
          PRE_RELEASE_VERSION="${VERSION_SPLIT[1]}"
          BUILD_VERSION="${VERSION_SPLIT[2]}"
          docker build -t ghcr.io/zeeshan50522/prime_number/python-demo-app:$MAIN_VERSION-$PRE_RELEASE_VERSION-$BUILD_VERSION-$GITHUB_SHA -t ghcr.io/zeeshan50522/prime_number/python-demo-app:$GITHUB_SHA .
          docker push ghcr.io/zeeshan50522/prime_number/python-demo-app:$MAIN_VERSION-$PRE_RELEASE_VERSION-$BUILD_VERSION-$GITHUB_SHA
         # docker push ghcr.io/zeeshan50522/python-demo-app
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: Build                   
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      
      - name: Setting Environment Variable
        run: bash scripts/update_github_env.sh

      - name: Checking Environment
        run: echo $ENVIRONMENT  
          
          
          
