name: python prime number github action

on:
  push:
    branches:
      - master
      - dev

    paths:
      - prime-number/**    
  workflow_dispatch:

jobs:
  Horusec:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
      - name: list repo
        run: ls -l
    
      - name: Downloading Horusec
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
     
      - name: list Horusec
        run: ls -l
      - name: Scanning Service
        run: horusec start -p "./prime-number" -o="json" -O="./results.json"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCEES_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCEES_KEY }}
          aws-region: us-east-1
      
      - name: aws s3 bucket list
        run: aws s3 ls
      

  Build:
    needs: [Horusec]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repo
        run: ls -l

      - name: Update build version
        run: |
          bash scripts/auto_increment_build.sh prime-number "build"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Incremented build version"
          add: '*'
