name: python prime number github action

on:
  push:
    branches:
      - master
      - dev

    paths:
      - prime-number/**    
  workflow_dispatch:

jobs:
  Horusec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repo list
        run: ls -l

  checking_code:
    needs: [Horusec]
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.1
        with:
          arguments: --config-file-path=horusec-config.json