name: python prime number github action

on:
  push:
    branches:
      - master
      - dev

    paths:
      - prime-number/**    
  workflow_dispatch:

jobs:
  Horusec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repo list
        run: ls -l

  checking_code:
    needs: [Horusec]
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Downloading Horusec
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
      - name: Scanning Service
        run: horusec start -p "./main" -o="json" -O="./results.json"
